In [12]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [3]:
users = pd.read_csv('BX-Users.csv', sep=';', encoding='latin-1')

In [14]:
users['Location_ID']=le.fit_transform(users.Location)

In [20]:
users.sort('Location')

C:\Users\Umbertojunior\Desktop\applicazioni usate\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':

,User-ID,Location,Age,Location_ID
118659,118660,"&#19978;&#28023;, shanghai, china",25.0,0
116874,116875,&#19978;&#28023;/&#21488;&#24030;/&#36335;&#26...,25.0,1
267048,267049,&#20013;&#22269;&#24191;&#19996;&#30465;&#2426...,NaN,2
245967,245968,&#20013;&#22269;&#27993;&#27743;&#30465;&#2770...,17.0,3
272618,272619,"&#20013;&#23665;&#24066;, puerto rico, hong kong",NaN,4
206114,206115,"&#20020;&#28023;, &#27993;&#27743;, china",NaN,5
278077,278078,"&#20029;&#27743;, &#20013;&#22269;-&#20113;&#2...",NaN,6
204009,204010,"&#20061;&#27743;, connecticut, croatia",18.0,7
220008,220009,"&#20975;&#37324;, guizhou, china",18.0,8
277490,277491,"&#21271;&#20140;, &#24191;&#35199;, china",18.0,9
245510,245511,"&#21271;&#20140;, berlin, china",NaN,10
97756,97757,"&#21271;&#20140;, west virginia, costa rica",20.0,11
116417,116418,"&#21335;&#20140;, &#27743;&#33487;, china",23.0,12
179017,179018,"&#21335;&#20140;, n/a, china",23.0,13
164547,164548,"&#21335;&#20805;, &#22235;&#24029;, china",19.0,14
271841,271842,"&#21512;&#32933;, ,",18.0,15
92746,92747,"&#21513;&#26519;, wyoming, china",23.0,16
275529,275530,"&#21608;&#26449;, alaska, china",22.0,17
116384,116385,"&#21688;&#38451;, &#38485;&#35199;, china",18.0,18
239885,239886,"&#22235;&#24029;&#30473;&#23665;, &#22235;&#24...",16.0,19
28098,28099,"&#22235;&#24029;, n, china",18.0,20
48298,48299,"&#22823;&#36830;, n/a, china",20.0,21
124783,124784,"&#24034;&#28246;, anhui, china",NaN,22
96144,96145,"&#24120;&#24503;, &#28246;&#21335;, china",NaN,23
87783,87784,"&#24191;&#24030;, new york, china",17.0,24
246880,246881,"&#24320;&#23553;, &#27827;&#21335;, china",21.0,25
270041,270042,"&#24464;&#24030;&#24066;, &#27743;&#33487;&#30...",24.0,26
140239,140240,"&#24576;&#21270;, &#28246;&#21335;, china",NaN,27
271371,271372,"&#25104;&#37117;, &#22235;&#24029;&#25104;&#37...",20.0,28
75604,75605,"&#25196;&#24030;, dc, china",21.0,29
...,...,...,...,...
125953,125954,"überlingen, baden-wuerttemberg, germany",43.0,57324
8328,8329,"überlingen, baden-wuerttemberg, germany",21.0,57324
198970,198971,"ýstanbul, , türkiye",NaN,57325
218116,218117,"ýstanbul, \n/a\"", turkey""",25.0,57326
275147,275148,"ýstanbul, alaska,",NaN,57327
127746,127747,"ýstanbul, marmara bölgesi, turkey",NaN,57328
36669,36670,"ýstanbul, marmara region, turkey,",NaN,57329
221791,221792,"ýstanbul, marmara, turkey",NaN,57330
176375,176376,"ýstanbul, marmara, turkey",15.0,57330
106321,106322,"ýstanbul, n/a, turkey",16.0,57331
19674,19675,"ýstanbul, n/a, turkey",NaN,57331
125151,125152,"ýstanbul, n/a, turkey",NaN,57331
36094,36095,"ýstanbul, n/a, turkey",NaN,57331
161589,161590,"ýstanbul, n/a, turkey",29.0,57331
14245,14246,"ýstanbul, n/a, turkey",NaN,57331
123692,123693,"ýstanbul, n/a, turkey",25.0,57331
79392,79393,"ýstanbul, ontario, turkey",NaN,57332
42852,42853,"ýstanbul, uk, turkey",NaN,57333
274463,274464,"ýstanbul, ýstanbul, turkey",25.0,57334
62259,62260,"ýstanbul, ýstanbul, turkey",28.0,57334
186661,186662,"ýstanbul, ýstanbul, turkey",NaN,57334
82758,82759,"ýstanbul, ýstanbul, turkey",25.0,57334
123830,123831,"ýstanbul, ýstanbul, turkey",25.0,57334
243276,243277,"ýstanbul, ýstanbul/anadolu, turkey",32.0,57335
268023,268024,"ýzmir, connecticut, turkey",27.0,57336
6161,6162,"ýzmir, n/a, turkey",25.0,57337
106233,106234,"ýzmir, n/a, turkey",20.0,57337
278594,278595,"ýzmir, n/a, turkey",NaN,57337
188909,188910,"ýzmir, n/a, turkey",NaN,57337
184163,184164,"ýzmýr, n/a, turkey",30.0,57338